version: '2'

services:
  api-frontend:
    build:
      context: ./server/
      dockerfile: docker/frontend/Dockerfile
    ports:
      - 8080:80
    depends_on:
      - api-backend


  api-backend:
    build:
      context: ./server/
      dockerfile: docker/backend/Dockerfile

