app <- ShinyDriver$new("../")
app$snapshotInit("mytest")

app$setInputs(algorithm = "ALGORITHM1_1")
app$setInputs(formula = "FORMULA_1_1_1")
app$setInputs(calculate = "click")
app$setInputs(formula = "FORMULA_1_1_5")
app$setInputs(calculate = "click")
app$setInputs(formula = "ALL")
app$setInputs(calculate = "click")
app$setInputs(algorithm = "ALL")
app$setInputs(calculate = "click")
app$setInputs(calculate = "click")
app$setInputs(method = "METHOD2")
app$setInputs(calculate = "click")
app$snapshot()
