FROM php:7.4-cli

RUN apt-get update && apt-get install -y libudunits2-dev libgdal-dev software-properties-common build-essential tzdata bash nodejs npm curl libfreetype6-dev dirmngr libpng-dev libjpeg-dev libzip-dev dirmngr apt-transport-https \
    && docker-php-ext-configure gd --with-freetype --with-jpeg \
    && docker-php-ext-install -j$(nproc) gd iconv mysqli pdo_mysql sockets zip

#RUN pecl install parallel
#RUN apt-key adv --keyserver keys.gnupg.net --recv-key 'E19F5F87128899B192B1A2C2AD5F960A256A04AF'
#RUN add-apt-repository 'deb http://cloud.r-project.org/bin/linux/debian buster-cran35/'
RUN apt-get update
RUN apt-get install -yf r-base libgmp3-dev libmpfr-dev libgdal-dev
RUN R -e "install.packages('dplyr', repos='http://cran.rstudio.com/')"
RUN R -e "install.packages('shiny', repos='http://cran.rstudio.com/')"
RUN R -e "install.packages('shiny.i18n', repos='http://cran.rstudio.com/')"
RUN R -e "install.packages('gmp', repos='http://cran.rstudio.com/')"
RUN R -e "install.packages('readr', repos='http://cran.rstudio.com/')"
RUN R -e "install.packages('geosphere', repos='http://cran.rstudio.com/')"
RUN R -e "install.packages('igraph', repos='http://cran.rstudio.com/')"
RUN R -e "install.packages('jsonlite', repos='http://cran.rstudio.com/')"
RUN R -e "install.packages('vroom', repos='http://cran.rstudio.com/')"
RUN R -e "install.packages('utf8', repos='http://cran.rstudio.com/')"
RUN R -e "install.packages('remotes', repos='http://cran.rstudio.com/')"
RUN R -e "install.packages('R.utils', repos='http://cran.rstudio.com/')"
RUN R -e "install.packages('leaflet', repos='http://cran.rstudio.com/')"
RUN R -e "install.packages('https://cran.r-project.org/src/contrib/Archive/SDMTools/SDMTools_1.1-221.2.tar.gz', repos=NULL, type='source')"
RUN R -e "install.packages('pheatmap', repos='http://cran.rstudio.com/')"
RUN R -e "install.packages('rjson', repos='http://cran.rstudio.com/')"
RUN R -e "install.packages('stringi', repos='http://cran.rstudio.com/')"
RUN R -e "install.packages('units', repos='http://cran.rstudio.com/')"
RUN R -e "install.packages('sf', repos='http://cran.rstudio.com/')"
RUN R -e "install.packages('systemfonts', repos='http://cran.rstudio.com/')"
RUN R -e "install.packages('svglite', repos='http://cran.rstudio.com/')"
RUN R -e "install.packages('leafpop', repos='http://cran.rstudio.com/')"
#RUN R -e "install.packages('mapview', repos='http://cran.rstudio.com/')"
#RUN R -e "install.packages('Rmpfr', repos='http://cran.rstudio.com/')"


RUN echo 'memory_limit = 4G' >> /usr/local/etc/php/conf.d/docker-php-memlimit.ini;
RUN echo 'max_execution_time = 0' >> /usr/local/etc/php/conf.d/docker-php-maxexectime.ini;
#RUN npm install -g gulp-cli

#Prepare application
COPY . /opt/calculations
WORKDIR /opt/calculations
ENV ENV prod
ENTRYPOINT php bin/console.php RunCalculationWorker
